language: csharp
solution: MonoAGS.sln

matrix:
  include: 
    - os: linux
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
    - os: osx
      mono: latest
      env: BUILD_CONFIG=DesktopRelease BUILD_PLATFORM="Any CPU"
 
install:
 - nuget restore MonoAGS.sln
 - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
 - xbuild /p:Configuration=$BUILD_CONFIG /p:Platform="$BUILD_PLATFORM" MonoAGS.sln
 - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Source/Tests/bin/Release/Tests.dll